config/routes.rb
Rails.application.routes.draw do

  root "toppage#top"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post 'guest_login', to: "guest_sessions#create"
  resources :users do
    get 'mypage', on: :collection
    get 'empathy', on: :collection
  end

  resources :posts do
    get 'draft', on: :collection
    get 'empathy', on: :collection
    resource :empathy, only: %i[create destroy]
  end

  get '/index', to:'posts#index'

  resource :polices, only: [] do
    collection do
      get :privacy
      get :service
    end
  end

  namespace :admin do
    resources :users
    resources :posts
  end
end

app/views/shared/_footer.html.erb
<ul class="footer">
  <li><%= link_to "プライバシーポリシー", privacy_polices_path %></li>
  <li><%= link_to "利用規約", service_polices_path %></li>
  <li><%= debug(params) if Rails.env.development? %></li>
</ul>

app/views/shared/_header.html.erb
<nav class="navbar navbar-dark bg-dark" style="height: 70px;">
  <div class="navbar-logo">
    <%= image_tag 'logo.png',  size: '50x50' %>
    <% if logged_in? %>
      <%= link_to "museum-app", index_path, class: "navbar-brand" %>
    <% else %>
      <%= link_to "museum-app", root_path, class: "navbar-brand" %>
    <% end %>
  </div>
  <ul class="navbar-nav d-none d-lg-flex flex-row">
    <% if logged_in? %>
      <li><a class="btn btn-secondary headerbtn" href="/posts/new" role="button" >新規投稿</a></li>
      <li>
        <div class="dropdown headerbtn" id='dropdown'>
          <button type="button" class="btn btn-secondary dropdown-toggle headerbtn" data-bs-toggle="dropdown" aria-expanded="false">
            マイページ
          </button>
          <ul class="dropdown-menu " id='dropdown-menu'>
            <li><a class="dropdown-item" href="/users/mypage">自身の作品</a></li>
            <li><a class="dropdown-item" href="/users/empathy">共感一覧</a></li>
            <li><a class="dropdown-item" href="/posts/draft">下書き一覧</a></li>
          </ul>
        </div>
      </li>
      <li>
        <div class="btn btn-secondary headerbtn">
          <%= button_to 'ログアウト', logout_path, method: :delete, form: { data: { turbo_confirm: "本当に削除しますか？", turbo_frame: '_top' } } ,class:"logoutbtn"%>
        </div>
      </li>
    <% else %>
      <div class="navbar-nav d-none d-lg-flex flex-row">
        <li><a class="btn btn-secondary headerbtn" href="/login" role="button" >ログイン</a></li>
        <li><a class="btn btn-secondary headerbtn" href="/users/new" role="button" >新規作成</a></li>
      </div>
    <% end %>
  </ul>
</nav>