config/routes.rb
Rails.application.routes.draw do

  root "toppage#top"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post 'guest_login', to: "guest_sessions#create"
  resources :users do
    get 'mypage', on: :collection
    get 'empathy', on: :collection
  end

  resources :posts do
    get 'draft', on: :collection
    get 'empathy', on: :collection
    resource :empathy, only: %i[create destroy]
  end

  get '/index', to:'posts#index'

  resource :polices, only: [] do
    collection do
      get :privacy
      get :service
    end
  end

  namespace :admin do
    resources :users
    resources :posts
  end
end

app/models/post.rb
class Post < ApplicationRecord
  #require 'open-uri'
  require 'aws-sdk-s3'
  mount_uploader :image, ImageUploader
  before_save :add_frame

  belongs_to :user, foreign_key: "user_id", class_name: "User"
  has_many :empathies
  has_one_attached :image

  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true, length: { maximum: 4000 }
  validates :image, presence: true

  enum status: { published: 0, draft: 1 }

  def empathize_by?(user)
    empathies.where(user_id: user.id).exists?
  end

  private

  def add_frame
    return unless image.present?

    # 投稿画像のパス
    input_path = image.url
    # 額縁画像のパス
    s3 = Aws::S3::Resource.new(region: 'ap-northeast-1')
    obj = s3.bucket('museum1-app').object('uploads/frame.png')
    url = obj.presigned_url(:get)
    Rails.logger.info "frame___path"
    # 投稿画像を読み込む
    image = MiniMagick::Image.open(input_path)
    image.resize "210x280!"
    Rails.logger.info "image open"
    # 額縁画像を読み込む
    frame = MiniMagick::Image.open(url)
    frame.resize "210x280!"
    Rails.logger.info "frame open"
    # 投稿画像と額縁画像を合成する
    result = image.composite(frame) do |c|
      c.compose "Over"
    end
    Rails.logger.info "compose___ok"
    # 合成した画像を保存する
    output_filename = "#{Time.now.to_i}.png"
    output_path = Rails.root.join("public", "uploads", "post", "image", output_filename)
    result.write(output_path)
    self.compose_image = "/uploads/post/image/#{output_filename}"
    Rails.logger.info "outpath__ok"
  end
end

#https://museum1-app.s3.ap-northeast-1.amazonaws.com/uploads/frame.png?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEPP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDmFwLW5vcnRoZWFzdC0xIkcwRQIgSQNRQKxLZjHrnnXR%2FAdYcyOpIqGIX5QMPJ%2BfNMUXl9kCIQCeVkJC9vHuDuYPeMcbR%2B2jz9qo%2BMxck6xTdHM9v2mhpirxAgjM%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BEAAaDDI5NDMzMDUxMDE4MiIMZe0FJia4%2Bh1IQ4OFKsUCDDUlfTuejTBg4YFl9ZXAdJ4eU6wD3wllZonoW9JlUWJib4yvpGb6pzDFB4%2FsWUfP%2FPpj10GP%2FwA1V2rcr1CRNnm24JvGASnXQ%2BtvojOPKjWZqcNMTNZSg98V9qV5kqa%2FHXCiy0LW6nmj3OBn02TVFE5CvlZSfiSTYo1WL%2BSSy%2F26uem8uy3rzhlUxPPKp39WXB3frnlHFquqS51DAtUX9HP2N6GWX9VmV70AMmiO57q1V%2FZvC2wb4aTNUXaUlC2u5a6uJUOk5J3V4zvQXnoD8Hrpcj2ezzmbz1yT8I8DqL%2FmjvuUZaGtnCoEexLj4ciHoFh5CBEByz7Q711%2FpugujN6UbV5YLxzLXnmJ98UWetFr1TlhcMBpTfUvhKfSe%2BdjHgJmiisy5zbKDf2Ke9plRulk19P9C1YHCY%2FThU1I1fGzSry4dDCY3%2FSnBjqzAkEkAaHsvMPWxIYNzFnFRz1xao3EGoisflX2RUvCojSsKcKgbmqtHsDrk27qERiQWrddDP3rMvvrBkjpHiIys14tarwAs7ZOyagkovgMIEV9S7atmf5kGjJFibirdDslHEbOq753cJXfPZ67JZUKjA6IFzeIulPT8SRQswzZamqC6iAhZ%2BrAD1HRERpqDUg8FbB5iXplVvqnzOfG7yaRSYdSM5Tt53DBemruNKS56qr8S0MLw2iFN9Pii%2F7yhWYvfsx5IGERU2Nuj6vE3SBr%2FAY2Ptlgycu6juwxnxMSl8KNEBVi8kOzLSlhnHbe3B5lXRTCmZFio6vsGmUXZyMLP4jbzlWIkjeMcQOxFIIOK0wVIQvRyYD4q8GGjJ1ve2JPRjbeLvg32Izg%2BONFd3mUKn53Le4%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230910T091738Z&X-Amz-SignedHeaders=host&X-Amz-Expires=600&X-Amz-Credential=ASIAUJB3XFNTHADO4RSB%2F20230910%2Fap-northeast-1%2Fs3%2Faws4_request&X-Amz-Signature=d6ccec15f95d17aee37e68fae6450be61ad289a568167c1cb1de1961a30d7412

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end
  private
  def post_params
    params.require(:post).permit(:body, :image, :status, :title, :empathy)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.published.order(created_at: :desc).page(params[:page]).per(10)
  end

  def show; end

  def new
    @post =Post.new
  end

  def create
    @post = current_user.posts.build(new_post_params)
    if @post.save
      redirect_to index_path
    else
      @post = Post.new(new_post_params)
      flash.now[:danger] = "未入力があります。写真、題名、投稿内容すべて入力してください。下書きにするときも何か入れてください"
      render 'new'
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      flash[:success] = "編集しました"
      redirect_to draft_posts_path
    else
      render 'edit'
    end
  end

  def destroy
    if @post.destroy
      redirect_to mypage_users_path,flash: {danger: "投稿を削除しました"}
    end
  end

  def draft
    @post = current_user.posts.draft.order(created_at: :desc).page(params[:page]).per(10)
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:body, :image, :status, :title, :empathy,:compose_image)
  end

  def new_post_params
    params.require(:post).permit(:body, :image, :title,:status,:compose_image)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def render_empathy_icon(emotion, post_id)
    case emotion
    when :happy
      '😀'
    when :sad
      '😢'
    when :love
      '😍'
    when :anger
      '😤'
    else
      ''
    end
  end
end

app/views/admin/posts/_post.html.erb
<tr>
  <td>
    ID:<%= post.id %>
  </td>
  <td>
    <%= post.title %>
  </td>
  <td>
    <%= post.user.name %>
  </td>
  <td>
    <%= link_to "詳細", admin_post_path(post.id), class: 'btn btn-info' %>
    <%= link_to "編集", edit_admin_post_path(post.id), class: 'btn btn-success' %>
    <%= link_to "削除", "#", method: :delete, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/admin/posts/edit.html.erb
<h3 class="page-header">編集ページ</h3>
<div class="main">
  <%= form_with model:@post do |f| %>
    <div class="content-left">
      <div class='mt-3 mb-3'>
        <%= image_tag @post.image.url,size: '400x400' %>
      </div>
      <p><%= f.label :title,"題名" %></p>
      <p><%= f.text_area :title %></p>
    </div>
    <div class="content-light">
      <p><%= f.label :body,"投稿内容" %></p>
      <p><%= f.text_area :body %></p>
    </div>
    <div class="form-group">
      <%= f.select :status, Post.statuses.keys.map { |k| [t("enums.post.status.#{k}"),k]}, {}, {class: "custom-select w-25"} %>
    </div>
    <div><%= f.submit "OK", class: "btn btn-primary" %></div>
  <% end %>
</div>

app/views/admin/posts/index.html.erb
<div class="container mb-5 pt-2">
  <h3>投稿一覧<%=link_to "ユーザー一覧を見る", admin_users_path%></h3>
  <div class="row">
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped">
        <thead>
        <tr>
        </tr>
        </thead>
        <tbody>
        <%= render @posts %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="show">
  <%= form_with model:@post do |f| %>
    <ul class="show-group">
      <ul class="show-item-left">
        <ul class="show-image">
          <li class="show-frame">
            <%= image_tag("額縁.png", alt: "額縁", class: "show-frame-inner") %>
            <%= image_tag @post.image.url,class: "show-image-inner"%>
          </li>
        </ul>
      </ul>
      <ul class="show-item-right">
        <li class="show-title">
          <%= "題名:" + @post.title.truncate(15) %>
        </li>
        <li class="show-body">
          <%= @post.body %>
        </li>
        <li class="button">
          <%= render "posts/btn", post: @post %>
        </li>
      </ul>
    </ul>
  <% end %>
</div>