config/routes.rb
Rails.application.routes.draw do

  root "toppage#top"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post 'guest_login', to: "guest_sessions#create"
  resources :users do
    get 'mypage', on: :collection
    get 'empathy', on: :collection
  end

  resources :posts do
    get 'draft', on: :collection
    get 'empathy', on: :collection
    resource :empathy, only: %i[create destroy]
  end

  get '/index', to:'posts#index'

  resource :polices, only: [] do
    collection do
      get :privacy
      get :service
    end
  end

  namespace :admin do
    resources :users
    resources :posts
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :posts, dependent: :destroy
  has_many :empathies, dependent: :destroy


  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_user
  def index
    @users = User.all
    @posts = Post.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
  end
  def edit
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
    redirect_to root_path
    end
  end

  private
  def admin_user
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    log_in @user
    redirect_to posts_path
  end

  def show; end

  def edit; end

  def update
    if @user.update(user_update_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    if @user.destroy
      redirect_to root_path
    end
  end

  def mypage
    @posts = current_user.posts.published.order(created_at: :desc).page(params[:page]).per(10)
    @post_empathy = current_user.empathies.where.not(empathy: nil).includes(:post).order(created_at: :desc).page(params[:page]).per(10)
    @post_draft = current_user.posts.draft.order(created_at: :desc).page(params[:page]).per(10)
  end

  def empathy
    @post_happy = current_user.empathies.where(empathy: :happy).includes(:post).order(created_at: :desc).page(params[:page]).per(10)
    @post_sad = current_user.empathies.where(empathy: :sad).includes(:post).order(created_at: :desc).page(params[:page]).per(10)
    @post_love = current_user.empathies.where(empathy: :love).includes(:post).order(created_at: :desc).page(params[:page]).per(10)
    @post_anger = current_user.empathies.where(empathy: :anger).includes(:post).order(created_at: :desc).page(params[:page]).per(10)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email,:password,:password_confirmation, :name)
  end

  def user_update_params
    params.require(:user).permit(:email, :name)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_post.html.erb
<% @posts.each do |f| %>
  <table class="table table-bordered bg-white">
    <tr>
      <td>ID:<%= f.id %></td>
    </tr>
    <tr>
      <td>タイトル：<%= f.title %></td>
    </tr>
    <tr>
      <td>ユーザー名：<%= f.user.name %></td>
    </tr>
    <tr>
      <td>本文：<%= f.body %></td>
    </tr>
  <td>
    <%= link_to "詳細", admin_post_path(f.id), class: 'btn btn-info' %>
    <%= link_to "編集", edit_admin_post_path, class: 'btn btn-success' %>
    <%= link_to "削除", "#", method: :delete, class: 'btn btn-danger' %>
  </td>
<%end%>

app/views/admin/users/_user.html.erb
<tr>
  <td>
    ID:<%= user.id %>
  </td>
  <td>
    <%= user.name %>
  </td>
  <td>
    <%= link_to "詳細", admin_user_path(user), class: 'btn btn-info' %>
    <%= link_to "編集", edit_admin_user_path(user), class: 'btn btn-success' %>
    <%= link_to "削除", "#", method: :delete, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/admin/users/index.html.erb
<div class="container mb-5 pt-2">
  <h3 >ユーザー一覧<%=link_to "投稿一覧を見る", admin_posts_path%></h3>
  <div class="row">
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped">
        <thead>
        <tr>
        </tr>
        </thead>
        <tbody>
        <%= render @users %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container mb-5 pt-2">
  <h3 ><%= @user.name%>さんの投稿</h3>
  <div class="row">
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped">
        <thead>
        <tr>
        </tr>
        </thead>
        <tbody>
        <%= render "admin/users/post" %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
    </div>
  </div>
</div>